### ISSUE TITLE
vint 実行エラー?

### ISSUE THREAD

**Issue by KazuakiM** [Kuniwak/vint#140]
vintを実行した所、エラーが発生しましたのでご報告します。
Pythonに疎く、同様の問題が発生した人などいましたら教えて頂けると助かります。

* 環境
 * OS X Yosemite 10.10.5
 * vint cd23db2 (最新バージョン)
 * .vintrc.yaml 未使用

```shell
$ pip install --upgrade vim-vint
Requirement already up-to-date: vim-vint in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: ansicolor==0.2.4 in /usr/local/lib/python2.7/site-packages (from vim-vint)
Requirement already up-to-date: chardet==2.3.0 in /usr/local/lib/python2.7/site-packages (from vim-vint)
Requirement already up-to-date: enum34==1.0.4 in /usr/local/lib/python2.7/site-packages (from vim-vint)
Requirement already up-to-date: pathlib==1.0.1 in /usr/local/lib/python2.7/site-packages (from vim-vint)
Requirement already up-to-date: PyYAML==3.11 in /usr/local/lib/python2.7/site-packages (from vim-vint)
$ vint --color --style ./.vimrc
Traceback (most recent call last):
  File "/usr/local/bin/vint", line 7, in <module>
    from vint import main
  File "/usr/local/lib/python2.7/site-packages/vint/__init__.py", line 1, in <module>
    from vint.bootstrap import (
ImportError: No module named bootstrap
```

**Comment by Kuniwak** [comment]
@KazuakiM 長らく着手できず、すみませんでした。

この問題ですが、[pip の問題の可能性](http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread)がありそうです。
pip のアップグレード後、再現するかどうか確認してもらってもいいでしょうか。

また、再現する場合は以下のコマンドの結果を教えてください。

```console
$ which python
/usr/bin/python

$ python --version
Python 2.7.10

$ which pip
/usr/local/bin/pip

$ pip --version
pip 1.5.6 from /Library/Python/2.7/site-packages (python 2.7)
```

**Comment by KazuakiM** [comment]
お手数をお掛けしました。
おっしゃる通り、Pythonの環境がよろしくなかったようです。
一旦、pipのバージョンを最新に上げ、インストール済ライブラリを全て削除して再度行ったところ、vint動きました。
本当に申し訳ありませんでした!!

**Comment by Kuniwak** [comment]
よかったです！ :smiley:
