### ISSUE TITLE
Vint throwing exception on non-alpha options

### ISSUE THREAD

**Issue by joshbode** [Kuniwak/vint#186]
Vint is throwing an exception for non-alpha options (i.e. `[a-z]+`), which appear to be valid options in Neovim (e.g. `<F13>`).

For example, the following option (necessary to to get control-shift working in iTerm2.app for me) that overrides the "F13 key" to map hex codes (see this [post](http://www.daniellesucher.com/2014/04/24/my-new-favorite-vim-tmux-bug/)), e.g.

```
set <F13>=^[[25~
map  <F13> <S-CR>
map! <F13> <S-CR>
```

gives:

```
Traceback (most recent call last):
  File "/usr/local/bin/vint", line 11, in <module>
    sys.exit(main())
...
  File "/usr/local/lib/python3.5/site-packages/vint/linting/policy/prohibit_abbreviation_option.py", line 62, in is_valid
    option_name = re.match(r'[a-z]+', option_expr).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

I was able to work around it by replacing the option in `.vimrc` with

```
set t_F3=^[[25~
map  <F13> <S-CR>
map! <F13> <S-CR>
```

**Comment by blueyed** [comment]
With v0.3.20 I get:

```
Traceback (most recent call last):
  File "/home/daniel/Vcs/vint/.venv/bin/vint", line 11, in <module>
    load_entry_point('vim-vint', 'console_scripts', 'vint')()
  File "/home/daniel/Vcs/vint/vint/__init__.py", line 11, in main
    init_cli()
  File "/home/daniel/Vcs/vint/vint/bootstrap.py", line 22, in init_cli
    cli.start()
  File "/home/daniel/Vcs/vint/vint/linting/cli.py", line 27, in start
    violations = self._lint_all(env, config_dict)
  File "/home/daniel/Vcs/vint/vint/linting/cli.py", line 124, in _lint_all
    violations += linter.lint_file(file_path)
  File "/home/daniel/Vcs/vint/vint/linting/linter.py", line 115, in lint_file
    self._traverse(root_ast, path)
  File "/home/daniel/Vcs/vint/vint/linting/linter.py", line 138, in _traverse
    self._prepare_for_traversal()
  File "/home/daniel/Vcs/vint/vint/linting/linter.py", line 155, in _prepare_for_traversal
    self._update_listeners_map()
  File "/home/daniel/Vcs/vint/vint/linting/linter.py", line 209, in _update_listeners_map
    self._update_enabled_policies()
  File "/home/daniel/Vcs/vint/vint/linting/linter.py", line 205, in _update_enabled_policies
    policy_set.update_by_config(config_dict)
  File "/home/daniel/Vcs/vint/vint/linting/policy_set.py", line 68, in update_by_config
    policy_enabling_map = self._get_enabling_map(config_dict)
  File "/home/daniel/Vcs/vint/vint/linting/policy_set.py", line 47, in _get_enabling_map
    policy_enabling_map[policy_name] = is_level_enabled(policy.level, severity)
  File "/home/daniel/Vcs/vint/vint/linting/level.py", line 12, in is_level_enabled
    return level.value <= base_lebel.value
AttributeError: 'NoneType' object has no attribute 'value'
```

Fixed in bf5a33f.

The initial error appears to have been fixed before then already.
