### ISSUE TITLE
linting/policy/prohibit_abbreviation_option.py: list index out of range

### ISSUE THREAD

**Issue by nfnty** [Kuniwak/vint#190]
Crashes when running `vint --style-problem delimitMate/autoload/delimitMate.vim`

```
Traceback (most recent call last):
  File "/usr/bin/vint", line 11, in <module>
    load_entry_point('vim-vint==0.3.10', 'console_scripts', 'vint')()
  File "/usr/lib/python3.5/site-packages/vint/__init__.py", line 11, in main
    init_cli()
  File "/usr/lib/python3.5/site-packages/vint/bootstrap.py", line 22, in init_cli
    cli.start()
  File "/usr/lib/python3.5/site-packages/vint/linting/cli.py", line 27, in start
    violations = self._lint_all(env, config_dict)
  File "/usr/lib/python3.5/site-packages/vint/linting/cli.py", line 120, in _lint_all
    violations += linter.lint_file(file_path)
  File "/usr/lib/python3.5/site-packages/vint/linting/linter.py", line 129, in lint_file
    on_leave=lambda node: self._handle_leave(node, lint_context))
  File "/usr/lib/python3.5/site-packages/vint/ast/traversing.py", line 243, in traverse
    node[prop_name])
  File "/usr/lib/python3.5/site-packages/vint/ast/traversing.py", line 9, in for_each
    call_if_def(func, node)
  File "/usr/lib/python3.5/site-packages/vint/ast/traversing.py", line 23, in call_if_def
    func(node)
  File "/usr/lib/python3.5/site-packages/vint/ast/traversing.py", line 242, in <lambda>
    accessor_func(lambda child_node: traverse(child_node, on_enter, on_leave),
  File "/usr/lib/python3.5/site-packages/vint/ast/traversing.py", line 243, in traverse
    node[prop_name])
  File "/usr/lib/python3.5/site-packages/vint/ast/traversing.py", line 9, in for_each
    call_if_def(func, node)
  File "/usr/lib/python3.5/site-packages/vint/ast/traversing.py", line 23, in call_if_def
    func(node)
  File "/usr/lib/python3.5/site-packages/vint/ast/traversing.py", line 242, in <lambda>
    accessor_func(lambda child_node: traverse(child_node, on_enter, on_leave),
  File "/usr/lib/python3.5/site-packages/vint/ast/traversing.py", line 233, in traverse
    should_traverse_children = on_enter(node) is not SKIP_CHILDREN
  File "/usr/lib/python3.5/site-packages/vint/linting/linter.py", line 128, in <lambda>
    on_enter=lambda node: self._handle_enter(node, lint_context),
  File "/usr/lib/python3.5/site-packages/vint/linting/linter.py", line 136, in _handle_enter
    self._fire_listeners(node, lint_context)
  File "/usr/lib/python3.5/site-packages/vint/linting/linter.py", line 154, in _fire_listeners
    violation = listening_policy.get_violation_if_found(node, lint_context)
  File "/usr/lib/python3.5/site-packages/vint/linting/policy/abstract_policy.py", line 38, in get_violation_if_found
    if self.is_valid(node, lint_context):
  File "/usr/lib/python3.5/site-packages/vint/linting/policy/prohibit_abbreviation_option.py", line 59, in is_valid
    option_expr = excmd_node['str'].split()[1]
IndexError: list index out of range
```

**Comment by Kuniwak** [comment]
Thanks for reporting this issue.
And sorry for my late reply.

I want to see the file `delimitMate.vim` to investigate this problem.
Could you comment the URL for the file, please?

**Comment by nfnty** [comment]
https://github.com/Raimondi/delimitMate/blob/master/autoload/delimitMate.vim
