### ISSUE TITLE
KeyError: 'USERCMD' with `Neomake! dummy`

### ISSUE THREAD

**Issue by blueyed** [Kuniwak/vint#224]
A line like `Neomake! dummy` will cause a KeyError:

```
Traceback (most recent call last):
  File "/usr/bin/vint", line 11, in <module>
    load_entry_point('vim-vint==0.3.13', 'console_scripts', 'vint')()
  File "/usr/lib/python3.6/site-packages/vint/__init__.py", line 11, in main
    init_cli()
  File "/usr/lib/python3.6/site-packages/vint/bootstrap.py", line 22, in init_cli
    cli.start()
  File "/usr/lib/python3.6/site-packages/vint/linting/cli.py", line 27, in start
    violations = self._lint_all(env, config_dict)
  File "/usr/lib/python3.6/site-packages/vint/linting/cli.py", line 120, in _lint_all
    violations += linter.lint_file(file_path)
  File "/usr/lib/python3.6/site-packages/vint/linting/linter.py", line 106, in lint_file
    root_ast = self._parser.parse_file(path)
  File "/usr/lib/python3.6/site-packages/vint/ast/parsing.py", line 61, in parse_file
    return self.parse(decoded_and_lf_normalized)
  File "/usr/lib/python3.6/site-packages/vint/ast/parsing.py", line 32, in parse
    ast = parser.parse(reader)
  File "/usr/lib/python3.6/site-packages/vint/_bundles/vimlparser.py", line 582, in parse
    self.parse_one_cmd()
  File "/usr/lib/python3.6/site-packages/vint/_bundles/vimlparser.py", line 608, in parse_one_cmd
    self.parse_command()
  File "/usr/lib/python3.6/site-packages/vint/_bundles/vimlparser.py", line 805, in parse_command
    if not viml_eqregh(self.ea.cmd.flags, "\\<BANG\\>") and self.ea.forceit and not viml_eqregh(self.ea.cmd.flags, "USERCMD"):
  File "/usr/lib/python3.6/site-packages/vint/_bundles/vimlparser.py", line 99, in viml_eqregh
    return re.search(pat_vim2py[reg], s)
KeyError: 'USERCMD'
```

**Comment by blueyed** [comment]
It's a vimlparser issue, will forward it there.

**Comment by wilywampa** [comment]
I get the same error when parsing the following code:

```vim
silent! TextobjLineDefaultKeyMappings!
```

**Comment by still-dreaming-1** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=45863039)](https://www.bountysource.com/issues/45863039-keyerror-usercmd-with-neomake-dummy?utm_source=45863039&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by brycepg** [comment]
Fixed by 7885aea12d71dd322fdbc2d99c64e24c2c602cb7

**Comment by blueyed** [comment]
Yep, fixed on master - thanks!

**Comment by blueyed** [comment]
Confirmed to be 7885aea.

@rhysd 
You should claim the bounty (see above).

**Comment by rhysd** [comment]
@blueyed 
Thank you for mentioning me! I didn't notice that.
But I want @Kuniwak to take the bounty since he is continuously improving vint. I feel he is more suitable.
