### ISSUE TITLE
Got  "ValueError: 92 is not a valid NodeType" with vint 0.3.13

### ISSUE THREAD

**Issue by machakann** [Kuniwak/vint#227]
Hello, thank you for your nice software.

Today I tried the latest version, and I got the following error message:

```
{USERPROFILE}>vint test.vim
Traceback (most recent call last):
  File "{USERPROFILE}\AppData\Local\Programs\Python\Python36-32\Scripts\vint-script.py", line 11, in <module>
    load_entry_point('vim-vint==0.3.13', 'console_scripts', 'vint')()
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\__init__.py", line 11, in main
    init_cli()
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\bootstrap.py", line 22, in init_cli
    cli.start()
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\linting\cli.py", line 27, in start
    violations = self._lint_all(env, config_dict)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\linting\cli.py", line 120, in _lint_all
    violations += linter.lint_file(file_path)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\linting\linter.py", line 106, in lint_file
    root_ast = self._parser.parse_file(path)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\parsing.py", line 61, in parse_file
    return self.parse(decoded_and_lf_normalized)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\parsing.py", line 38, in parse
    plugin.process(ast)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\plugin\scope_plugin\__init__.py", line 32, in process
    processed_ast = self._ref_tester.process(ast)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\plugin\scope_plugin\reference_reachability_tester.py", line 43, in process
    scope_linker.process(ast)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\plugin\scope_plugin\scope_linker.py", line 312, in process
    attached_ast = id_classifier.attach_identifier_attributes(ast)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\plugin\scope_plugin\identifier_classifier.py", line 122, in attach_identifier_attributes
    ast_with_parsed_redir = redir_assignment_parser.process(ast)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\plugin\scope_plugin\redir_assignment_parser.py", line 33, in process
    traverse(ast, on_enter=enter_handler)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 243, in traverse
    node[prop_name])
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 9, in for_each
    call_if_def(func, node)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 23, in call_if_def
    func(node)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 242, in <lambda>
    accessor_func(lambda child_node: traverse(child_node, on_enter, on_leave),
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 243, in traverse
    node[prop_name])
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 23, in call_if_def
    func(node)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 242, in <lambda>
    accessor_func(lambda child_node: traverse(child_node, on_enter, on_leave),
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 243, in traverse
    node[prop_name])
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 9, in for_each
    call_if_def(func, node)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 23, in call_if_def
    func(node)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 242, in <lambda>
    accessor_func(lambda child_node: traverse(child_node, on_enter, on_leave),
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\site-packages\vint\ast\traversing.py", line 227, in traverse
    node_type = NodeType(node['type'])
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\enum.py", line 533, in __new__
    return cls._missing_(value)
  File "{USERPROFILE}\appdata\local\programs\python\python36-32\lib\enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 92 is not a valid NodeType
```

with the following Vim script code ({USERPROFILE}\test.vim).

```vim
let l = ['a', 'aa', 'aaa']
call sort(l, {a, b -> strchars(a) - strchars(b)})
```

I've edited a part of path ({USERPROFILE}). I remember that I've gotten a lint error with the previous version but it seems now it throws an exception. Sorry I'm not so clear about python, please tell me if there is anything I should tell.

OS: Windows 10 64bit Home edition
```
{USERPROFILE}>python -V
Python 3.6.1

{USERPROFILE}>vint -v
0.3.13
```

**Comment by lambdalisue** [comment]
Same here.
