### ISSUE TITLE
vint errors on unicode characters

### ISSUE THREAD

**Issue by JackeJR** [Kuniwak/vint#242]
I was using vint.exe on my vimrc when it kept giving me the following error message:

```
Traceback (most recent call last):
  File "C:\Env\Python3\Scripts\vint-script.py", line 11, in <module>
    load_entry_point('vim-vint==0.3.14', 'console_scripts', 'vint')()
  File "c:\env\python3\lib\site-packages\vint\__init__.py", line 11, in main
    init_cli()
  File "c:\env\python3\lib\site-packages\vint\bootstrap.py", line 22, in init_cli
    cli.start()
  File "c:\env\python3\lib\site-packages\vint\linting\cli.py", line 27, in start
    violations = self._lint_all(env, config_dict)
  File "c:\env\python3\lib\site-packages\vint\linting\cli.py", line 120, in _lint_all
    violations += linter.lint_file(file_path)
  File "c:\env\python3\lib\site-packages\vint\linting\linter.py", line 106, in lint_file
    root_ast = self._parser.parse_file(path)
  File "c:\env\python3\lib\site-packages\vint\ast\parsing.py", line 58, in parse_file
    decoded = bytes_seq.decode(encoding)
  File "c:\env\python3\lib\encodings\cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8e in position 2939: character maps to <undefined>
```
By trial and error, I narrowed it down to the character: 𝒮
When I removed the line containing the character, all is well.

System: Win 10 Pro x64, python36 x64, cmd codepage 65001
Vint was installed using pip.

**Comment by Kuniwak** [comment]
Maybe duplicated #225

**Comment by tyru** [comment]
@li-ruijie it was fixed already.
