### ISSUE TITLE
using command with ! at the end causes vint to crash

### ISSUE THREAD

**Issue by still-dreaming-1** [Kuniwak/vint#244]
If any file, say, nothing.init.vim, contains this code:
```
call plug#begin()
Plug 'metakirby5/codi.vim'
call plug#end()
Codi!!
```
And then you vint it via `vint nothing.init.vim`, the following crash error is shown:
```
Traceback (most recent call last):
  File "/home/jesse/.local/bin/vint", line 11, in <module>
    sys.exit(main())
  File "/home/jesse/.local/lib/python2.7/site-packages/vint/__init__.py", line 11, in main
    init_cli()
  File "/home/jesse/.local/lib/python2.7/site-packages/vint/bootstrap.py", line 22, in init_cli
    cli.start()
  File "/home/jesse/.local/lib/python2.7/site-packages/vint/linting/cli.py", line 27, in start
    violations = self._lint_all(env, config_dict)
  File "/home/jesse/.local/lib/python2.7/site-packages/vint/linting/cli.py", line 120, in _lint_all
    violations += linter.lint_file(file_path)
  File "/home/jesse/.local/lib/python2.7/site-packages/vint/linting/linter.py", line 106, in lint_file
    root_ast = self._parser.parse_file(path)
  File "/home/jesse/.local/lib/python2.7/site-packages/vint/ast/parsing.py", line 61, in parse_file
    return self.parse(decoded_and_lf_normalized)
  File "/home/jesse/.local/lib/python2.7/site-packages/vint/ast/parsing.py", line 32, in parse
    ast = parser.parse(reader)
  File "/home/jesse/.local/lib/python2.7/site-packages/vint/_bundles/vimlparser.py", line 582, in parse
    self.parse_one_cmd()
  File "/home/jesse/.local/lib/python2.7/site-packages/vint/_bundles/vimlparser.py", line 608, in parse_one_cmd
    self.parse_command()
  File "/home/jesse/.local/lib/python2.7/site-packages/vint/_bundles/vimlparser.py", line 805, in parse_command
    if not viml_eqregh(self.ea.cmd.flags, "\\<BANG\\>") and self.ea.forceit and not viml_eqregh(self.ea.cmd.flags, "USERCMD"):
  File "/home/jesse/.local/lib/python2.7/site-packages/vint/_bundles/vimlparser.py", line 99, in viml_eqregh
    return re.search(pat_vim2py[reg], s)
KeyError: 'USERCMD
```
Actually the error occurs if the only line is `Codi!!` or even `Codi!`, but I put the other lines in to put a little context around the reason I want to put an `!` at the end of a command is because this is a real command supported by the [Codi](https://github.com/metakirby5/codi.vim) plugin.

**Comment by still-dreaming-1** [comment]
I realize this is not exactly helpful, but just showing it is a real thing, this appears to be the line of code defining this command in that plugin `command! -nargs=? -bang -bar -complete=filetype Codi call codi#run(<bang>0, <f-args>)`

**Comment by still-dreaming-1** [comment]
Duplicate of https://github.com/Kuniwak/vint/issues/224
