### ISSUE TITLE
ModuleNotFoundError: No module named 'cerf_api'

### ISSUE THREAD

**Issue by dnebauer** [Kuniwak/vint#247]
Installed vint with `pip install --upgrade vint` which ended with the message:

```sh
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 docopt-0.6.2 idna-2.6 python-dateutil-2.6.1 requests-2.18.4 six-1.11.0 urllib3-1.22 vint-0.1.5
```

Running vint from the console results in the following error traceback:

```sh
Traceback (most recent call last):
  File "/home/user/.local/bin/vint", line 13, in <module>
    from vint import vint
  File "/home/user/.local/lib/python3.6/site-packages/vint/vint.py", line 5, in <module>
    from cerf_api import Cerf
ModuleNotFoundError: No module named 'cerf_api'
```

**Comment by Kuniwak** [comment]
The correct package name of Vint is `vim-vint`.
Please upgrade vint the following command:

```console
$ pip install --upgrade vim-vint
```

**Comment by dnebauer** [comment]
Ouch. Stupid mistake on my part. Hopefully this issue will help anyone else who makes it. Thanks for your quick response.
