### ISSUE TITLE
Linting scripts from stdin is broken

### ISSUE THREAD

**Issue by ebkalderon** [Kuniwak/vint#305]
## Environment

* `vint` 0.3.19
* Python 3.7.3
* macOS Mojave 10.14.3 (18D109)

## Description

It seems that linting Vim scripts from stdin sometimes fails, depending on the method of input used and whether the script contains errors or not.

### Script with warnings

1. Create a new file `has-warning.vim`.
2. Enter and save the following text: `autocmd FileType sh setlocal shiftwidth=2`. This should trigger a warning in the default `vint` configuration, but no errors.

`vint - < has-warning.vim` works fine, but `cat has-warning.vim | vint -` mysteriously crashes:

```
$ vint - < has-warning.vim
stdin:1:1: autocmd should execute in an augroup or execute with a group (see :help :autocmd)
$ cat has-warning.vim | vint -
Traceback (most recent call last):
  File "/usr/local/bin/vint", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/vint/__init__.py", line 11, in main
    init_cli()
  File "/usr/local/lib/python3.7/site-packages/vint/bootstrap.py", line 22, in init_cli
    cli.start()
  File "/usr/local/lib/python3.7/site-packages/vint/linting/cli.py", line 27, in start
    violations = self._lint_all(env, config_dict)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/cli.py", line 121, in _lint_all
    violations += linter.lint_text(sys.stdin.read())
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 132, in lint_text
    self._traverse(root_ast, 'stdin')
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 150, in _traverse
    on_leave=lambda node: self._handle_leave(node, lint_context))
  File "/usr/local/lib/python3.7/site-packages/vint/ast/traversing.py", line 234, in traverse
    should_traverse_children = on_enter(node) is not SKIP_CHILDREN
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 149, in <lambda>
    on_enter=lambda node: self._handle_enter(node, lint_context),
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 160, in _handle_enter
    self._fire_listeners(node, lint_context)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 178, in _fire_listeners
    violation = listening_policy.get_violation_if_found(node, lint_context)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/abstract_policy.py", line 38, in get_violation_if_found
    if self.is_valid(node, lint_context):
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/prohibit_missing_scriptencoding.py", line 36, in is_valid
    return not self._check_script_has_multibyte_char(lint_context)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/prohibit_missing_scriptencoding.py", line 54, in _check_script_has_multibyte_char
    return self._check_stdin_has_multibyte_char()
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/prohibit_missing_scriptencoding.py", line 64, in _check_stdin_has_multibyte_char
    sys.stdin.seek(0)
io.UnsupportedOperation: underlying stream is not seekable
```

### Script without warnings, errors, or style problems

1. Create a new file `no-issues.vim`.
2. Enter and save the following text: `set nonumber`.

Here, `vint` also crashes in the latter form of stdin input:

```
$ vint - < no-issues.vim
$ cat no-issues.vim | vint -
Traceback (most recent call last):
  File "/usr/local/bin/vint", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/vint/__init__.py", line 11, in main
    init_cli()
  File "/usr/local/lib/python3.7/site-packages/vint/bootstrap.py", line 22, in init_cli
    cli.start()
  File "/usr/local/lib/python3.7/site-packages/vint/linting/cli.py", line 27, in start
    violations = self._lint_all(env, config_dict)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/cli.py", line 121, in _lint_all
    violations += linter.lint_text(sys.stdin.read())
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 132, in lint_text
    self._traverse(root_ast, 'stdin')
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 150, in _traverse
    on_leave=lambda node: self._handle_leave(node, lint_context))
  File "/usr/local/lib/python3.7/site-packages/vint/ast/traversing.py", line 234, in traverse
    should_traverse_children = on_enter(node) is not SKIP_CHILDREN
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 149, in <lambda>
    on_enter=lambda node: self._handle_enter(node, lint_context),
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 160, in _handle_enter
    self._fire_listeners(node, lint_context)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 178, in _fire_listeners
    violation = listening_policy.get_violation_if_found(node, lint_context)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/abstract_policy.py", line 38, in get_violation_if_found
    if self.is_valid(node, lint_context):
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/prohibit_missing_scriptencoding.py", line 36, in is_valid
    return not self._check_script_has_multibyte_char(lint_context)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/prohibit_missing_scriptencoding.py", line 54, in _check_script_has_multibyte_char
    return self._check_stdin_has_multibyte_char()
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/prohibit_missing_scriptencoding.py", line 64, in _check_stdin_has_multibyte_char
    sys.stdin.seek(0)
io.UnsupportedOperation: underlying stream is not seekable
```

### Script with errors

1. Create a new file `has-error.vim`.
2. Enter and save the following text: `foo`. This should trigger an error in the default `vint` configuration.

Strangely, both forms of stdin input behave as expected when there are errors:

```
$ vint - < has-error.vim
stdin:1:1: E492: Not an editor command: foo (see vim-jp/vim-vimlparser)
$ cat has-error.vim | vint -
stdin:1:1: E492: Not an editor command: foo (see vim-jp/vim-vimlparser)
```

Any idea what could be going on here?

**Comment by blueyed** [comment]
I believe that's fixed on master, can you try?

**Comment by ebkalderon** [comment]
@blueyed Sweet, it behaves as expected on `master`. Is there a new release on the way soon? I am running into issues properly integrating `vint` into my editor with the version currently available via `pip`.

**Comment by blueyed** [comment]
Cool, closing then.

Unfortunately @Kuniwak seems to have disappeared.  IIRC I could do a release, but do not have the time/energy for this currently myself - I think some work needs to be done for v4 still.

**Comment by ebkalderon** [comment]
I see, I suppose I will stick to tracking the source in `master` in the meantime. Thank you for continuing to maintain the project!

**Comment by Moshem123** [comment]
The package installed from brew can't parse input from stdin:
https://pasteboard.co/JCJf2BA.png

Will there be a fix?

**Comment by blueyed** [comment]
@Moshem123 
It still needs a new release to be made I think.
You can use HEAD/master for now.

**Comment by Moshem123** [comment]
Thanks,
This helped me: https://github.com/iamcco/coc-diagnostic/issues/62
