### ISSUE TITLE
Linting from stdin is crashed.

### ISSUE THREAD

**Issue by steelbluelee** [Kuniwak/vint#332]
I installed vim-vint using "pip3 install using "pip3 install vim-vint --user" on ubuntu 19.04.
vint version is 0.3.21

When I run "vint - < .vimrc", I have the following result.

sklee@ubuntu:~$ vint - < .vimrc
Traceback (most recent call last):
  File "/usr/local/bin/vint", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/vint/__init__.py", line 11, in main
    init_cli()
  File "/usr/local/lib/python3.7/dist-packages/vint/bootstrap.py", line 22, in init_cli
    cli.start()
  File "/usr/local/lib/python3.7/dist-packages/vint/linting/cli.py", line 27, in start
    violations = self._lint_all(env, config_dict)
  File "/usr/local/lib/python3.7/dist-packages/vint/linting/cli.py", line 121, in _lint_all
    violations += linter.lint_text(sys.stdin.read())
  File "/usr/local/lib/python3.7/dist-packages/vint/linting/linter.py", line 132, in lint_text
    self._traverse(root_ast, 'stdin')
  File "/usr/local/lib/python3.7/dist-packages/vint/linting/linter.py", line 150, in _traverse
    on_leave=lambda node: self._handle_leave(node, lint_context))
  File "/usr/local/lib/python3.7/dist-packages/vint/ast/traversing.py", line 244, in traverse
    node[prop_name])
  File "/usr/local/lib/python3.7/dist-packages/vint/ast/traversing.py", line 9, in for_each
    call_if_def(func, node)
  File "/usr/local/lib/python3.7/dist-packages/vint/ast/traversing.py", line 23, in call_if_def
    func(node)
  File "/usr/local/lib/python3.7/dist-packages/vint/ast/traversing.py", line 243, in <lambda>
    accessor_func(lambda child_node: traverse(child_node, on_enter, on_leave),
  File "/usr/local/lib/python3.7/dist-packages/vint/ast/traversing.py", line 234, in traverse
    should_traverse_children = on_enter(node) is not SKIP_CHILDREN
  File "/usr/local/lib/python3.7/dist-packages/vint/linting/linter.py", line 149, in <lambda>
    on_enter=lambda node: self._handle_enter(node, lint_context),
  File "/usr/local/lib/python3.7/dist-packages/vint/linting/linter.py", line 160, in _handle_enter
    self._fire_listeners(node, lint_context)
  File "/usr/local/lib/python3.7/dist-packages/vint/linting/linter.py", line 178, in _fire_listeners
    violation = listening_policy.get_violation_if_found(node, lint_context)
  File "/usr/local/lib/python3.7/dist-packages/vint/linting/policy/abstract_policy.py", line 38, in get_violation_if_found
    if self.is_valid(node, lint_context):
  File "/usr/local/lib/python3.7/dist-packages/vint/linting/policy/prohibit_no_abort_function.py", line 27, in is_valid
    if 'autoload' not in lint_context['path'].parts:
AttributeError: 'str' object has no attribute 'parts'

And, "cat .vimrc | vint -" produces the same result.

But, "vint .vimrc" works well.

What should I check?

thx

**Comment by steelbluelee** [comment]
Installing master branch in this repository solved the problem.

**Comment by blueyed** [comment]
Thanks for the report and reporting back.
Closing then.
